// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqMKjlYw99b3TDqQhjaz6ofB0H18I43Mc',
    appId: '1:481676215854:web:ad00de6df7c46fd13941bf',
    messagingSenderId: '481676215854',
    projectId: 'expensage',
    authDomain: 'expensage.firebaseapp.com',
    storageBucket: 'expensage.appspot.com',
    measurementId: 'G-5TR0HWVCFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlTwngcYe9BGiu1SZ9GPw4LxMn56gEHlQ',
    appId: '1:481676215854:android:b2637926bfd6953e3941bf',
    messagingSenderId: '481676215854',
    projectId: 'expensage',
    storageBucket: 'expensage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoNC8EN6bOUnYVJRtrY3qs1zX51PJ4qCw',
    appId: '1:481676215854:ios:b67c3f62ddf8c16a3941bf',
    messagingSenderId: '481676215854',
    projectId: 'expensage',
    storageBucket: 'expensage.appspot.com',
    iosBundleId: 'com.example.expensage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoNC8EN6bOUnYVJRtrY3qs1zX51PJ4qCw',
    appId: '1:481676215854:ios:aa04d004f9c64dc43941bf',
    messagingSenderId: '481676215854',
    projectId: 'expensage',
    storageBucket: 'expensage.appspot.com',
    iosBundleId: 'com.example.expensage.RunnerTests',
  );
}
